export const PARTIDO_COLORS = {
  'RN': '#1d6fce',
  'UDI': '#f59e0b',
  'Republicano': '#1e3a8a',
  'Evópoli': '#06b6d4',
  'DEM': '#9ca3af',
  'PS': '#dc2626',
  'PPD': '#f97316',
  'PDC': '#e879a0',
  'PC': '#7f1d1d',
  'FA': '#a855f7',
  'FREVS': '#22c55e',
  'Liberal': '#fbbf24',
  'Independiente': '#6b7280',
  'PDG': '#8b5cf6',
  'PNL': '#0ea5e9',
  'AH': '#10b981',
  'PR': '#ec4899',
}

export const senadores = [
  // OPOSICIÓN
  { nombre: 'Alfonso de Urresti', partido: 'PS', bloque: 'Oposición', region: 'Los Ríos', cargo: 'Senador' },
  { nombre: 'Juan Luis Castro', partido: 'PS', bloque: 'Oposición', region: 'O\'Higgins', cargo: 'Senador' },
  { nombre: 'Fidel Espinoza', partido: 'PS', bloque: 'Oposición', region: 'Los Lagos', cargo: 'Senador' },
  { nombre: 'Gastón Saavedra', partido: 'PS', bloque: 'Oposición', region: 'Biobío', cargo: 'Senador' },
  { nombre: 'Danisa Astudillo', partido: 'PS', bloque: 'Oposición', region: 'Tarapacá', cargo: 'Senadora' },
  { nombre: 'Daniella Cicardini', partido: 'PS', bloque: 'Oposición', region: 'Atacama', cargo: 'Senadora' },
  { nombre: 'Paulina Vodanovic', partido: 'PS', bloque: 'Oposición', region: 'La Araucanía', cargo: 'Senadora' },
  { nombre: 'Pedro Araya Guerrero', partido: 'PPD', bloque: 'Oposición', region: 'Antofagasta', cargo: 'Senador (Ind-PPD)' },
  { nombre: 'Loreto Carvajal', partido: 'PPD', bloque: 'Oposición', region: 'Ñuble', cargo: 'Senadora' },
  { nombre: 'Ricardo Celis', partido: 'PPD', bloque: 'Oposición', region: 'La Araucanía', cargo: 'Senador (Ind-PPD)' },
  { nombre: 'Ximena Órdenes', partido: 'PPD', bloque: 'Oposición', region: 'Aysén', cargo: 'Senadora (Ind-PPD)' },
  { nombre: 'Francisco Huenchumilla', partido: 'PDC', bloque: 'Oposición', region: 'La Araucanía', cargo: 'Senador' },
  { nombre: 'Iván Flores', partido: 'PDC', bloque: 'Oposición', region: 'Los Ríos', cargo: 'Senador' },
  { nombre: 'Yasna Provoste', partido: 'PDC', bloque: 'Oposición', region: 'Atacama', cargo: 'Senadora' },
  { nombre: 'Daniel Núñez', partido: 'PC', bloque: 'Oposición', region: 'Coquimbo', cargo: 'Senador' },
  { nombre: 'Claudia Pascual', partido: 'PC', bloque: 'Oposición', region: 'Metropolitana', cargo: 'Senadora' },
  { nombre: 'Karol Cariola', partido: 'PC', bloque: 'Oposición', region: 'Valparaíso', cargo: 'Senadora' },
  { nombre: 'Diego Ibáñez', partido: 'FA', bloque: 'Oposición', region: 'Valparaíso', cargo: 'Senador' },
  { nombre: 'Beatriz Sánchez', partido: 'FA', bloque: 'Oposición', region: 'La Araucanía', cargo: 'Senadora' },
  { nombre: 'Esteban Velásquez', partido: 'FREVS', bloque: 'Oposición', region: 'Antofagasta', cargo: 'Senador' },
  { nombre: 'Miguel Ángel Calisto', partido: 'FREVS', bloque: 'Oposición', region: 'Aysén', cargo: 'Senador (Ind-FRVS)' },
  { nombre: 'Vlado Mirosevic', partido: 'Liberal', bloque: 'Oposición', region: 'Arica y Parinacota', cargo: 'Senador' },
  { nombre: 'Fabiola Campillai', partido: 'Independiente', bloque: 'Oposición', region: 'Metropolitana', cargo: 'Senadora' },
  { nombre: 'Alejandra Sepúlveda', partido: 'Independiente', bloque: 'Oposición', region: 'O\'Higgins', cargo: 'Senadora' },
  { nombre: 'Karim Bianchi', partido: 'Independiente', bloque: 'Oposición', region: 'Magallanes', cargo: 'Senador' },
  // OFICIALISMO
  { nombre: 'Paulina Núñez Urrutia', partido: 'RN', bloque: 'Oficialismo', region: 'Antofagasta', cargo: 'Presidenta del Senado' },
  { nombre: 'Manuel José Ossandón', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', cargo: 'Senador' },
  { nombre: 'Andrés Longton', partido: 'RN', bloque: 'Oficialismo', region: 'Valparaíso', cargo: 'Senador' },
  { nombre: 'Camila Flores', partido: 'RN', bloque: 'Oficialismo', region: 'Valparaíso', cargo: 'Senadora' },
  { nombre: 'Miguel Becker', partido: 'RN', bloque: 'Oficialismo', region: 'La Araucanía', cargo: 'Senador' },
  { nombre: 'Andrea Balladares', partido: 'RN', bloque: 'Oficialismo', region: 'La Araucanía', cargo: 'Senadora' },
  { nombre: 'María José Gatica', partido: 'RN', bloque: 'Oficialismo', region: 'Los Lagos', cargo: 'Senadora' },
  { nombre: 'Carlos Kuschel', partido: 'RN', bloque: 'Oficialismo', region: 'Los Lagos', cargo: 'Senador' },
  { nombre: 'Alejandro Kusanovic', partido: 'RN', bloque: 'Oficialismo', region: 'Magallanes', cargo: 'Senador (Ind-RN)' },
  { nombre: 'Sergio Gahona', partido: 'RN', bloque: 'Oficialismo', region: 'Coquimbo', cargo: 'Senador' },
  { nombre: 'Rodrigo Galilea', partido: 'RN', bloque: 'Oficialismo', region: 'Maule', cargo: 'Senador' },
  { nombre: 'Iván Moreira', partido: 'UDI', bloque: 'Oficialismo', region: 'Los Lagos', cargo: 'Vicepresidente del Senado' },
  { nombre: 'Javier Macaya', partido: 'UDI', bloque: 'Oficialismo', region: 'O\'Higgins', cargo: 'Senador' },
  { nombre: 'Gustavo Sanhueza', partido: 'UDI', bloque: 'Oficialismo', region: 'Ñuble', cargo: 'Senador' },
  { nombre: 'Enrique van Rysselberghe', partido: 'UDI', bloque: 'Oficialismo', region: 'Biobío', cargo: 'Senador' },
  { nombre: 'Renzo Trisotti', partido: 'Republicano', bloque: 'Oficialismo', region: 'Tarapacá', cargo: 'Senador' },
  { nombre: 'Rodolfo Carter', partido: 'Republicano', bloque: 'Oficialismo', region: 'La Araucanía', cargo: 'Senador (Ind-REP)' },
  { nombre: 'Cristián Vial', partido: 'Republicano', bloque: 'Oficialismo', region: 'La Araucanía', cargo: 'Senador (Ind-REP)' },
  { nombre: 'Arturo Squella', partido: 'Republicano', bloque: 'Oficialismo', region: 'Valparaíso', cargo: 'Senador' },
  { nombre: 'Ignacio Urrutia', partido: 'Republicano', bloque: 'Oficialismo', region: 'La Araucanía', cargo: 'Senador' },
  { nombre: 'Luciano Cruz-Coke', partido: 'Evópoli', bloque: 'Oficialismo', region: 'Metropolitana', cargo: 'Senador' },
  { nombre: 'Sebastián Keitel', partido: 'Evópoli', bloque: 'Oficialismo', region: 'Los Lagos', cargo: 'Senador (Ind-EVO)' },
  { nombre: 'Matías Walker', partido: 'DEM', bloque: 'Oficialismo', region: 'Coquimbo', cargo: 'Senador' },
  { nombre: 'Enrique Lee', partido: 'DEM', bloque: 'Oficialismo', region: 'Arica y Parinacota', cargo: 'Senador (Ind-DEM)' },
  { nombre: 'Rojo Edwards', partido: 'Independiente', bloque: 'Oficialismo', region: 'Metropolitana', cargo: 'Senador' },
]

export const diputados = [
  { nombre: 'Luis Malla', partido: 'Liberal', bloque: 'Oposición', region: 'Arica y Parinacota', distrito: 1 },
  { nombre: 'Jorge Díaz Ibarra', partido: 'PDC', bloque: 'Oposición', region: 'Arica y Parinacota', distrito: 1 },
  { nombre: 'Stephanie Jéldrez', partido: 'Republicano', bloque: 'Oficialismo', region: 'Arica y Parinacota', distrito: 1 },
  { nombre: 'Carlos Carvajal Gallardo', partido: 'PPD', bloque: 'Oposición', region: 'Tarapacá', distrito: 2 },
  { nombre: 'Ximena Naranjo', partido: 'UDI', bloque: 'Oficialismo', region: 'Tarapacá', distrito: 2 },
  { nombre: 'Álvaro Jofré', partido: 'PNL', bloque: 'Oficialismo', region: 'Tarapacá', distrito: 2 },
  { nombre: 'Sebastián Videla', partido: 'Liberal', bloque: 'Oposición', region: 'Antofagasta', distrito: 3 },
  { nombre: 'Jaime Araya Guerrero', partido: 'PPD', bloque: 'Oposición', region: 'Antofagasta', distrito: 3 },
  { nombre: 'Marcela Hernando', partido: 'PR', bloque: 'Oposición', region: 'Antofagasta', distrito: 3 },
  { nombre: 'Fabián Ossandón', partido: 'PDG', bloque: 'Independiente', region: 'Antofagasta', distrito: 3 },
  { nombre: 'Carlo Arqueros', partido: 'Republicano', bloque: 'Oficialismo', region: 'Antofagasta', distrito: 3 },
  { nombre: 'Juan Santana', partido: 'PS', bloque: 'Oposición', region: 'Atacama', distrito: 4 },
  { nombre: 'Cristian Tapia Ramos', partido: 'PPD', bloque: 'Oposición', region: 'Atacama', distrito: 4 },
  { nombre: 'Jaime Mulet', partido: 'FREVS', bloque: 'Oposición', region: 'Atacama', distrito: 4 },
  { nombre: 'Paula Olmos', partido: 'PDG', bloque: 'Independiente', region: 'Atacama', distrito: 4 },
  { nombre: 'Ignacio Urcullu', partido: 'Republicano', bloque: 'Oficialismo', region: 'Atacama', distrito: 4 },
  { nombre: 'Daniel Manouchehri', partido: 'PS', bloque: 'Oposición', region: 'Coquimbo', distrito: 5 },
  { nombre: 'Nathalie Castillo', partido: 'PC', bloque: 'Oposición', region: 'Coquimbo', distrito: 5 },
  { nombre: 'Carolina Tello', partido: 'FA', bloque: 'Oposición', region: 'Coquimbo', distrito: 5 },
  { nombre: 'Marco Sulantay', partido: 'UDI', bloque: 'Oficialismo', region: 'Coquimbo', distrito: 5 },
  { nombre: 'Eileen Urquieta', partido: 'PDG', bloque: 'Independiente', region: 'Coquimbo', distrito: 5 },
  { nombre: 'Erich Grohs', partido: 'PNL', bloque: 'Oficialismo', region: 'Coquimbo', distrito: 5 },
  { nombre: 'Nelson Venegas Salazar', partido: 'PS', bloque: 'Oposición', region: 'Valparaíso', distrito: 6 },
  { nombre: 'Sofía González Cortés', partido: 'PC', bloque: 'Oposición', region: 'Valparaíso', distrito: 6 },
  { nombre: 'Cristian Mella', partido: 'PDC', bloque: 'Oposición', region: 'Valparaíso', distrito: 6 },
  { nombre: 'María Francisca Bello', partido: 'FA', bloque: 'Oposición', region: 'Valparaíso', distrito: 6 },
  { nombre: 'Chiara Barchiesi', partido: 'Republicano', bloque: 'Oficialismo', region: 'Valparaíso', distrito: 6 },
  { nombre: 'Luis Pardo Sainz', partido: 'RN', bloque: 'Oficialismo', region: 'Valparaíso', distrito: 6 },
  { nombre: 'Javier Olivares', partido: 'PDG', bloque: 'Independiente', region: 'Valparaíso', distrito: 6 },
  { nombre: 'Jaime Bassa', partido: 'FA', bloque: 'Oposición', region: 'Valparaíso', distrito: 7 },
  { nombre: 'Luis Cuello', partido: 'PC', bloque: 'Oposición', region: 'Valparaíso', distrito: 7 },
  { nombre: 'Luis Sánchez Ossa', partido: 'Republicano', bloque: 'Oficialismo', region: 'Valparaíso', distrito: 7 },
  { nombre: 'Hotuiti Teao', partido: 'UDI', bloque: 'Oficialismo', region: 'Valparaíso', distrito: 7 },
  { nombre: 'Andrés Celis', partido: 'RN', bloque: 'Oficialismo', region: 'Valparaíso', distrito: 7 },
  { nombre: 'Juan Marcelo Valenzuela', partido: 'PDG', bloque: 'Independiente', region: 'Valparaíso', distrito: 7 },
  { nombre: 'Gustavo Gatica', partido: 'PC', bloque: 'Oposición', region: 'Metropolitana', distrito: 8 },
  { nombre: 'Marcos Barraza', partido: 'PC', bloque: 'Oposición', region: 'Metropolitana', distrito: 8 },
  { nombre: 'Tatiana Urrutia', partido: 'FA', bloque: 'Oposición', region: 'Metropolitana', distrito: 8 },
  { nombre: 'Agustín Romero', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 8 },
  { nombre: 'Cristián Contreras Radovic', partido: 'PDG', bloque: 'Independiente', region: 'Metropolitana', distrito: 8 },
  { nombre: 'Mario Olavarría', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 8 },
  { nombre: 'Carlos Cuadrado Prats', partido: 'PPD', bloque: 'Oposición', region: 'Metropolitana', distrito: 9 },
  { nombre: 'Boris Barrera', partido: 'PC', bloque: 'Oposición', region: 'Metropolitana', distrito: 9 },
  { nombre: 'César Valenzuela Maass', partido: 'PS', bloque: 'Oposición', region: 'Metropolitana', distrito: 9 },
  { nombre: 'José Carlos Meza', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 9 },
  { nombre: 'Tamara Ramírez', partido: 'PDG', bloque: 'Independiente', region: 'Metropolitana', distrito: 9 },
  { nombre: 'Guillermo Ramírez Diez', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 9 },
  { nombre: 'Gonzalo Winter', partido: 'FA', bloque: 'Oposición', region: 'Metropolitana', distrito: 10 },
  { nombre: 'Irací Hassler', partido: 'PC', bloque: 'Oposición', region: 'Metropolitana', distrito: 10 },
  { nombre: 'José Antonio Kast Adriasola', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 10 },
  { nombre: 'Hans Marowski', partido: 'PNL', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 10 },
  { nombre: 'Francisco Orrego Gutiérrez', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 10 },
  { nombre: 'Jorge Alessandri Vergara', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 10 },
  { nombre: 'Diego Schalper', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11 },
  { nombre: 'Constanza Hube', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11 },
  { nombre: 'Catalina del Real', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11 },
  { nombre: 'Constanza Schönhaut', partido: 'FA', bloque: 'Oposición', region: 'Metropolitana', distrito: 11 },
  { nombre: 'Álvaro Carter', partido: 'Republicano', bloque: 'Oficialismo', region: 'O\'Higgins', distrito: 12 },
  { nombre: 'Pamela Jiles', partido: 'PDG', bloque: 'Independiente', region: 'O\'Higgins', distrito: 12 },
  { nombre: 'Ana María Gazmuri', partido: 'AH', bloque: 'Oposición', region: 'O\'Higgins', distrito: 12 },
  { nombre: 'Ximena Ossandón', partido: 'RN', bloque: 'Oficialismo', region: 'O\'Higgins', distrito: 12 },
  { nombre: 'Daniela Serrano', partido: 'PC', bloque: 'Oposición', region: 'O\'Higgins', distrito: 12 },
  { nombre: 'Gael Yeomans', partido: 'FA', bloque: 'Oposición', region: 'Maule', distrito: 13 },
  { nombre: 'Lorena Pizarro', partido: 'PC', bloque: 'Oposición', region: 'Maule', distrito: 13 },
  { nombre: 'Felipe Ross', partido: 'Republicano', bloque: 'Oficialismo', region: 'Maule', distrito: 13 },
  { nombre: 'Eduardo Durán', partido: 'RN', bloque: 'Oficialismo', region: 'Maule', distrito: 13 },
  { nombre: 'Ignacio Achurra', partido: 'FA', bloque: 'Oposición', region: 'Maule', distrito: 14 },
  { nombre: 'Marisela Santibáñez', partido: 'PC', bloque: 'Oposición', region: 'Maule', distrito: 14 },
  { nombre: 'Raúl Leiva', partido: 'PS', bloque: 'Oposición', region: 'Maule', distrito: 14 },
  { nombre: 'Diego Vergara', partido: 'Republicano', bloque: 'Oficialismo', region: 'Maule', distrito: 14 },
  { nombre: 'Jaime Coloma', partido: 'UDI', bloque: 'Oficialismo', region: 'Maule', distrito: 14 },
  { nombre: 'Raúl Soto', partido: 'PPD', bloque: 'Oposición', region: 'Ñuble', distrito: 15 },
  { nombre: 'Valentina Cáceres', partido: 'FA', bloque: 'Oposición', region: 'Ñuble', distrito: 15 },
  { nombre: 'Natalia Romero', partido: 'UDI', bloque: 'Oficialismo', region: 'Ñuble', distrito: 15 },
  { nombre: 'Fernando Ugarte Tejeda', partido: 'Republicano', bloque: 'Oficialismo', region: 'Ñuble', distrito: 15 },
  { nombre: 'Carolina Cucumides', partido: 'PS', bloque: 'Oposición', region: 'Biobío', distrito: 16 },
  { nombre: 'Félix Bugueño', partido: 'FA', bloque: 'Oposición', region: 'Biobío', distrito: 16 },
  { nombre: 'Ricardo Neumann', partido: 'UDI', bloque: 'Oficialismo', region: 'Biobío', distrito: 16 },
  { nombre: 'Sebastián Cristoffanini', partido: 'Republicano', bloque: 'Oficialismo', region: 'Biobío', distrito: 16 },
  { nombre: 'Priscilla Castillo', partido: 'PDC', bloque: 'Oposición', region: 'Biobío', distrito: 17 },
  { nombre: 'Roberto Celedón', partido: 'FA', bloque: 'Oposición', region: 'Biobío', distrito: 17 },
  { nombre: 'Benjamín Moreno Bascur', partido: 'Republicano', bloque: 'Oficialismo', region: 'Biobío', distrito: 17 },
  { nombre: 'Jorge Guzmán Zepeda', partido: 'Evópoli', bloque: 'Oficialismo', region: 'Biobío', distrito: 17 },
  { nombre: 'Cristián Menchaca', partido: 'Republicano', bloque: 'Oficialismo', region: 'La Araucanía', distrito: 18 },
  { nombre: 'Consuelo Veloso', partido: 'PR', bloque: 'Oposición', region: 'La Araucanía', distrito: 18 },
  { nombre: 'Rodrigo Ramírez Parra', partido: 'RN', bloque: 'Oficialismo', region: 'La Araucanía', distrito: 18 },
  { nombre: 'Cristóbal Martínez', partido: 'UDI', bloque: 'Oficialismo', region: 'La Araucanía', distrito: 19 },
  { nombre: 'Carlos Chandía', partido: 'RN', bloque: 'Oficialismo', region: 'La Araucanía', distrito: 19 },
  { nombre: 'Felipe Camaño', partido: 'PDC', bloque: 'Oposición', region: 'La Araucanía', distrito: 19 },
  { nombre: 'Francisco Crisóstomo', partido: 'PS', bloque: 'Oposición', region: 'La Araucanía', distrito: 19 },
  { nombre: 'Sara Concha', partido: 'Independiente', bloque: 'Oficialismo', region: 'La Araucanía', distrito: 19 },
  { nombre: 'Francesca Muñoz', partido: 'Republicano', bloque: 'Oficialismo', region: 'Los Ríos', distrito: 20 },
  { nombre: 'Paz Charpentier', partido: 'Republicano', bloque: 'Oficialismo', region: 'Los Ríos', distrito: 20 },
  { nombre: 'Marlene Pérez', partido: 'UDI', bloque: 'Oficialismo', region: 'Los Ríos', distrito: 20 },
  { nombre: 'Álvaro Ortiz Vera', partido: 'PDC', bloque: 'Oposición', region: 'Los Ríos', distrito: 20 },
  { nombre: 'Antonio Rivas Villalobos', partido: 'PS', bloque: 'Oposición', region: 'Los Ríos', distrito: 20 },
  { nombre: 'Patricio Briones', partido: 'PDG', bloque: 'Independiente', region: 'Los Ríos', distrito: 20 },
  { nombre: 'Flor Weisse', partido: 'UDI', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 21 },
  { nombre: 'Joanna Pérez', partido: 'DEM', bloque: 'Oposición', region: 'Los Lagos', distrito: 21 },
  { nombre: 'Cristóbal Urruticoechea', partido: 'PNL', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 21 },
  { nombre: 'Patricio Pinilla', partido: 'PDC', bloque: 'Oposición', region: 'Los Lagos', distrito: 21 },
  { nombre: 'Eduardo Cretton', partido: 'UDI', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 22 },
  { nombre: 'Juan Carlos Beltrán', partido: 'RN', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 22 },
  { nombre: 'Gloria Naveillán', partido: 'PNL', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 22 },
  { nombre: 'Andrea Parra', partido: 'PPD', bloque: 'Oposición', region: 'Los Lagos', distrito: 22 },
  { nombre: 'José Montalva', partido: 'PPD', bloque: 'Oposición', region: 'Aysén', distrito: 23 },
  { nombre: 'Ericka Ñanco', partido: 'FA', bloque: 'Oposición', region: 'Aysén', distrito: 23 },
  { nombre: 'Stephan Schubert', partido: 'Republicano', bloque: 'Oficialismo', region: 'Aysén', distrito: 23 },
  { nombre: 'Tomás Kast', partido: 'Evópoli', bloque: 'Oficialismo', region: 'Aysén', distrito: 23 },
  { nombre: 'René Manuel García', partido: 'RN', bloque: 'Oficialismo', region: 'Aysén', distrito: 23 },
  { nombre: 'Marcos Ilabaca', partido: 'PS', bloque: 'Oposición', region: 'Los Ríos', distrito: 24 },
  { nombre: 'Matías Fernández Hartwig', partido: 'FA', bloque: 'Oposición', region: 'Los Ríos', distrito: 24 },
  { nombre: 'Omar Sabat', partido: 'UDI', bloque: 'Oficialismo', region: 'Los Ríos', distrito: 24 },
  { nombre: 'Leandro Kunstmann', partido: 'Republicano', bloque: 'Oficialismo', region: 'Los Ríos', distrito: 24 },
  { nombre: 'Héctor Barría', partido: 'PDC', bloque: 'Oposición', region: 'Los Lagos', distrito: 25 },
  { nombre: 'Emilia Nuyado', partido: 'PS', bloque: 'Oposición', region: 'Los Lagos', distrito: 25 },
  { nombre: 'Daniel Lilayu', partido: 'UDI', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 25 },
  { nombre: 'Paulina Muñoz', partido: 'PNL', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 25 },
  { nombre: 'Alejandro Bernales', partido: 'Liberal', bloque: 'Oposición', region: 'Magallanes', distrito: 26 },
  { nombre: 'Héctor Ulloa', partido: 'PPD', bloque: 'Oposición', region: 'Magallanes', distrito: 26 },
  { nombre: 'Mauro González Villarroel', partido: 'RN', bloque: 'Oficialismo', region: 'Magallanes', distrito: 26 },
  { nombre: 'Claudia Reyes Larenas', partido: 'Republicano', bloque: 'Oficialismo', region: 'Magallanes', distrito: 26 },
  { nombre: 'Álex Nahuelquín', partido: 'PDG', bloque: 'Independiente', region: 'Magallanes', distrito: 26 },
  { nombre: 'Andrea Macías', partido: 'PS', bloque: 'Oposición', region: 'Aysén', distrito: 27 },
  { nombre: 'René Alinco', partido: 'FREVS', bloque: 'Oposición', region: 'Aysén', distrito: 27 },
  { nombre: 'Alejandra Valdebenito', partido: 'UDI', bloque: 'Oficialismo', region: 'Aysén', distrito: 27 },
  { nombre: 'Carlos Bianchi', partido: 'Independiente', bloque: 'Independiente', region: 'Magallanes', distrito: 28 },
  { nombre: 'Alejandro Riquelme', partido: 'Republicano', bloque: 'Oficialismo', region: 'Magallanes', distrito: 28 },
  { nombre: 'Javiera Morales', partido: 'FA', bloque: 'Oposición', region: 'Magallanes', distrito: 28 },
  // Distrito 5 faltantes
  { nombre: 'Bernardo Salinas', partido: 'Independiente', bloque: 'Oficialismo', region: 'Coquimbo', distrito: 5 },
  // Distrito 7 faltante
  { nombre: 'Sebastián Zamora', partido: 'Republicano', bloque: 'Oficialismo', region: 'Valparaíso', distrito: 7 },
  // Distrito 8 faltante
  { nombre: 'Enrique Bassaletti', partido: 'Independiente', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 8 },
  // Distrito 9 faltante
  { nombre: 'Javiera Rodríguez', partido: 'Independiente', bloque: 'Oposición', region: 'Metropolitana', distrito: 9 },
  // Distrito 10 faltante
  { nombre: 'Emilia Schneider', partido: 'FA', bloque: 'Oposición', region: 'Metropolitana', distrito: 10 },
  // Distrito 11 faltantes
  { nombre: 'Cristián Araya', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11 },
  { nombre: 'Claudia Mora Vega', partido: 'Independiente', bloque: 'Oposición', region: 'Metropolitana', distrito: 11 },
  // Distrito 12 faltante
  { nombre: 'Benjamín Lorca', partido: 'Independiente', bloque: 'Oposición', region: 'O\'Higgins', distrito: 12 },
  // Distrito 13 faltante
  { nombre: 'Valentina Becerra', partido: 'Independiente', bloque: 'Oposición', region: 'Maule', distrito: 13 },
  // Distrito 14 faltante
  { nombre: 'Juan Irarrázaval', partido: 'Independiente', bloque: 'Oficialismo', region: 'Maule', distrito: 14 },
  // Distrito 17 faltante
  { nombre: 'Javier Muñoz Riquelme', partido: 'Independiente', bloque: 'Oposición', region: 'Biobío', distrito: 17 },
  // Distrito 19 faltante
  { nombre: 'Sergio Bobadilla', partido: 'UDI', bloque: 'Oficialismo', region: 'La Araucanía', distrito: 19 },
]
