export const PARTIDO_COLORS = {
  'RN': '#1d6fce',
  'UDI': '#f59e0b',
  'Republicano': '#1e3a8a',
  'EvÃ³poli': '#06b6d4',
  'DEM': '#9ca3af',
  'PS': '#dc2626',
  'PPD': '#f97316',
  'PDC': '#e879a0',
  'PC': '#7f1d1d',
  'FA': '#7c3aed',
  'FREVS': '#22c55e',
  'Liberal': '#fbbf24',
  'Independiente': '#e5e7eb',
  'PDG': '#ea580c',
  'PNL': '#0ea5e9',
  'AH': '#10b981',
  'PSC': '#f43f5e',
}

export const senadores = [
  // OPOSICIÃ“N (25)
  { nombre: 'Alfonso de Urresti', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Los RÃ­os', cargo: 'Senador' },
  { nombre: 'Juan Luis Castro', partido: 'PS', bloque: 'OposiciÃ³n', region: "O'Higgins", cargo: 'Senador' },
  { nombre: 'Fidel Espinoza', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Los Lagos', cargo: 'Senador' },
  { nombre: 'GastÃ³n Saavedra', partido: 'PS', bloque: 'OposiciÃ³n', region: 'BiobÃ­o', cargo: 'Senador' },
  { nombre: 'Danisa Astudillo', partido: 'PS', bloque: 'OposiciÃ³n', region: 'TarapacÃ¡', cargo: 'Senadora' },
  { nombre: 'Daniella Cicardini', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Atacama', cargo: 'Senadora' },
  { nombre: 'Paulina Vodanovic', partido: 'PS', bloque: 'OposiciÃ³n', region: 'La AraucanÃ­a', cargo: 'Senadora' },
  { nombre: 'Pedro Araya Guerrero', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'Antofagasta', cargo: 'Senador (Ind-PPD)' },
  { nombre: 'Loreto Carvajal', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'Ã‘uble', cargo: 'Senadora' },
  { nombre: 'Ricardo Celis', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'La AraucanÃ­a', cargo: 'Senador (Ind-PPD)' },
  { nombre: 'Ximena Ã“rdenes', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'AysÃ©n', cargo: 'Senadora (Ind-PPD)' },
  { nombre: 'Francisco Huenchumilla', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'La AraucanÃ­a', cargo: 'Senador' },
  { nombre: 'IvÃ¡n Flores', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'Los RÃ­os', cargo: 'Senador' },
  { nombre: 'Yasna Provoste', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'Atacama', cargo: 'Senadora' },
  { nombre: 'Daniel NÃºÃ±ez', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Coquimbo', cargo: 'Senador' },
  { nombre: 'Claudia Pascual', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Metropolitana', cargo: 'Senadora' },
  { nombre: 'Karol Cariola', partido: 'PC', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', cargo: 'Senadora' },
  { nombre: 'Diego IbÃ¡Ã±ez', partido: 'FA', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', cargo: 'Senador' },
  { nombre: 'Beatriz SÃ¡nchez', partido: 'FA', bloque: 'OposiciÃ³n', region: 'La AraucanÃ­a', cargo: 'Senadora' },
  { nombre: 'Esteban VelÃ¡squez', partido: 'FREVS', bloque: 'OposiciÃ³n', region: 'Antofagasta', cargo: 'Senador' },
  { nombre: 'Miguel Ãngel Calisto', partido: 'FREVS', bloque: 'OposiciÃ³n', region: 'AysÃ©n', cargo: 'Senador (Ind-FRVS)' },
  { nombre: 'Vlado Mirosevic', partido: 'Liberal', bloque: 'OposiciÃ³n', region: 'Arica y Parinacota', cargo: 'Senador' },
  { nombre: 'Fabiola Campillai', partido: 'Independiente', bloque: 'OposiciÃ³n', region: 'Metropolitana', cargo: 'Senadora' },
  { nombre: 'Alejandra SepÃºlveda', partido: 'Independiente', bloque: 'OposiciÃ³n', region: "O'Higgins", cargo: 'Senadora' },
  { nombre: 'Karim Bianchi', partido: 'Independiente', bloque: 'OposiciÃ³n', region: 'Magallanes', cargo: 'Senador' },
  // OFICIALISMO (25)
  { nombre: 'Paulina NÃºÃ±ez Urrutia', partido: 'RN', bloque: 'Oficialismo', region: 'Antofagasta', cargo: 'Presidenta del Senado' },
  { nombre: 'Manuel JosÃ© OssandÃ³n', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', cargo: 'Senador' },
  { nombre: 'AndrÃ©s Longton', partido: 'RN', bloque: 'Oficialismo', region: 'ValparaÃ­so', cargo: 'Senador' },
  { nombre: 'Camila Flores', partido: 'RN', bloque: 'Oficialismo', region: 'ValparaÃ­so', cargo: 'Senadora' },
  { nombre: 'Miguel Becker', partido: 'RN', bloque: 'Oficialismo', region: 'La AraucanÃ­a', cargo: 'Senador' },
  { nombre: 'Andrea Balladares', partido: 'RN', bloque: 'Oficialismo', region: 'La AraucanÃ­a', cargo: 'Senadora' },
  { nombre: 'MarÃ­a JosÃ© Gatica', partido: 'RN', bloque: 'Oficialismo', region: 'Los Lagos', cargo: 'Senadora' },
  { nombre: 'Carlos Kuschel', partido: 'RN', bloque: 'Oficialismo', region: 'Los Lagos', cargo: 'Senador' },
  { nombre: 'Alejandro Kusanovic', partido: 'RN', bloque: 'Oficialismo', region: 'Magallanes', cargo: 'Senador (Ind-RN)' },
  { nombre: 'Sergio Gahona', partido: 'RN', bloque: 'Oficialismo', region: 'Coquimbo', cargo: 'Senador' },
  { nombre: 'Rodrigo Galilea', partido: 'RN', bloque: 'Oficialismo', region: 'Maule', cargo: 'Senador' },
  { nombre: 'IvÃ¡n Moreira', partido: 'UDI', bloque: 'Oficialismo', region: 'Los Lagos', cargo: 'Vicepresidente del Senado' },
  { nombre: 'Javier Macaya', partido: 'UDI', bloque: 'Oficialismo', region: "O'Higgins", cargo: 'Senador' },
  { nombre: 'Gustavo Sanhueza', partido: 'UDI', bloque: 'Oficialismo', region: 'Ã‘uble', cargo: 'Senador' },
  { nombre: 'Enrique van Rysselberghe', partido: 'UDI', bloque: 'Oficialismo', region: 'BiobÃ­o', cargo: 'Senador' },
  { nombre: 'Renzo Trisotti', partido: 'Republicano', bloque: 'Oficialismo', region: 'TarapacÃ¡', cargo: 'Senador' },
  { nombre: 'Rodolfo Carter', partido: 'Republicano', bloque: 'Oficialismo', region: 'La AraucanÃ­a', cargo: 'Senador (Ind-REP)' },
  { nombre: 'CristiÃ¡n Vial', partido: 'Republicano', bloque: 'Oficialismo', region: 'La AraucanÃ­a', cargo: 'Senador (Ind-REP)' },
  { nombre: 'Arturo Squella', partido: 'Republicano', bloque: 'Oficialismo', region: 'ValparaÃ­so', cargo: 'Senador' },
  { nombre: 'Ignacio Urrutia', partido: 'Republicano', bloque: 'Oficialismo', region: 'La AraucanÃ­a', cargo: 'Senador' },
  { nombre: 'Luciano Cruz-Coke', partido: 'EvÃ³poli', bloque: 'Oficialismo', region: 'Metropolitana', cargo: 'Senador' },
  { nombre: 'SebastiÃ¡n Keitel', partido: 'EvÃ³poli', bloque: 'Oficialismo', region: 'Los Lagos', cargo: 'Senador (Ind-EVO)' },
  { nombre: 'MatÃ­as Walker', partido: 'DEM', bloque: 'Oficialismo', region: 'Coquimbo', cargo: 'Senador' },
  { nombre: 'Enrique Lee', partido: 'DEM', bloque: 'Oficialismo', region: 'Arica y Parinacota', cargo: 'Senador (Ind-DEM)' },
  { nombre: 'Rojo Edwards', partido: 'Independiente', bloque: 'Oficialismo', region: 'Metropolitana', cargo: 'Senador' },
]

// Regiones por distrito (oficial Servel)
// D1: Arica y Parinacota, D2: TarapacÃ¡, D3: Antofagasta, D4: Atacama, D5: Coquimbo
// D6: ValparaÃ­so, D7: ValparaÃ­so, D8: Metropolitana, D9: Metropolitana, D10: Metropolitana
// D11: Metropolitana, D12: Metropolitana, D13: Metropolitana, D14: Metropolitana
// D15: O'Higgins, D16: O'Higgins, D17: Maule, D18: Maule, D19: Ã‘uble
// D20: BiobÃ­o, D21: BiobÃ­o, D22: La AraucanÃ­a, D23: La AraucanÃ­a
// D24: Los RÃ­os, D25: Los Lagos, D26: Los Lagos, D27: AysÃ©n, D28: Magallanes

export const diputados = [
  // D1 - Arica y Parinacota
  { nombre: 'Luis Malla Valenzuela', partido: 'Liberal', bloque: 'OposiciÃ³n', region: 'Arica y Parinacota', distrito: 1, votos: 29127, porcentaje: '21,54%' },
  { nombre: 'Jorge DÃ­az Ibarra', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'Arica y Parinacota', distrito: 1, votos: 18558, porcentaje: '13,72%' },
  { nombre: 'Stephanie JÃ©ldrez Ortiz', partido: 'Republicano', bloque: 'Oficialismo', region: 'Arica y Parinacota', distrito: 1, votos: 12471, porcentaje: '9,22%' },
  // D2 - TarapacÃ¡
  { nombre: 'Carlos Carvajal Gallardo', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'TarapacÃ¡', distrito: 2, votos: 25360, porcentaje: '13,89%' },
  { nombre: 'Ximena Naranjo Pinto', partido: 'UDI', bloque: 'Oficialismo', region: 'TarapacÃ¡', distrito: 2, votos: 19298, porcentaje: '10,57%' },
  { nombre: 'Ãlvaro JofrÃ© CÃ¡ceres', partido: 'PNL', bloque: 'Oficialismo', region: 'TarapacÃ¡', distrito: 2, votos: 17898, porcentaje: '8,16%' },
  // D3 - Antofagasta
  { nombre: 'SebastiÃ¡n Videla Castillo', partido: 'Liberal', bloque: 'OposiciÃ³n', region: 'Antofagasta', distrito: 3, votos: 74340, porcentaje: '23,31%' },
  { nombre: 'Jaime Araya Guerrero', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'Antofagasta', distrito: 3, votos: 13604, porcentaje: '4,27%' },
  { nombre: 'Marcela Hernando PÃ©rez', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'Antofagasta', distrito: 3, votos: 11944, porcentaje: '3,74%' },
  { nombre: 'FabiÃ¡n OssandÃ³n BriceÃ±o', partido: 'PDG', bloque: 'Independiente', region: 'Antofagasta', distrito: 3, votos: 33161, porcentaje: '10,40%' },
  { nombre: 'Carlo Arquero Pizarro', partido: 'Republicano', bloque: 'Oficialismo', region: 'Antofagasta', distrito: 3, votos: 12464, porcentaje: '3,91%' },
  // D4 - Atacama
  { nombre: 'Jaime Mulet MartÃ­nez', partido: 'FREVS', bloque: 'OposiciÃ³n', region: 'Atacama', distrito: 4, votos: 25525, porcentaje: '11,91%' },
  { nombre: 'Cristian Tapia Ramos', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'Atacama', distrito: 4, votos: 18154, porcentaje: '10,53%' },
  { nombre: 'Juan Santana Castillo', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Atacama', distrito: 4, votos: 19335, porcentaje: '11,22%' },
  { nombre: 'Paula Olmos Contreras', partido: 'PDG', bloque: 'Independiente', region: 'Atacama', distrito: 4, votos: 9975, porcentaje: '5,79%' },
  { nombre: 'Ignacio Clement-Lund', partido: 'Republicano', bloque: 'Oficialismo', region: 'Atacama', distrito: 4, votos: 8375, porcentaje: '4,86%' },
  // D5 - Coquimbo
  { nombre: 'Carolina Tello Rojas', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Coquimbo', distrito: 5, votos: 15047, porcentaje: '3,37%' },
  { nombre: 'Daniel Manouchehri Moghadam', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Coquimbo', distrito: 5, votos: 94501, porcentaje: '21,16%' },
  { nombre: 'Nathalie Castillo Rojas', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Coquimbo', distrito: 5, votos: 19290, porcentaje: '4,32%' },
  { nombre: 'Bernardo Salinas Maya', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Coquimbo', distrito: 5, votos: 3802, porcentaje: '0,85%' },
  { nombre: 'Eileen Urquieta Rojas', partido: 'PDG', bloque: 'Independiente', region: 'Coquimbo', distrito: 5, votos: 15660, porcentaje: '3,51%' },
  { nombre: 'Marco Sulantay Olivares', partido: 'UDI', bloque: 'Oficialismo', region: 'Coquimbo', distrito: 5, votos: 22781, porcentaje: '5,10%' },
  { nombre: 'Erich Grohs MarÃ­n', partido: 'PNL', bloque: 'Oficialismo', region: 'Coquimbo', distrito: 5, votos: 13502, porcentaje: '3,02%' },
  // D6 - ValparaÃ­so (interior)
  { nombre: 'Nelson Venegas Salazar', partido: 'PS', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', distrito: 6, votos: 38426, porcentaje: '6,49%' },
  { nombre: 'SofÃ­a GonzÃ¡lez CortÃ©s', partido: 'PC', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', distrito: 6, votos: 33227, porcentaje: '5,65%' },
  { nombre: 'MarÃ­a Francisca Bello Campos', partido: 'FA', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', distrito: 6, votos: 30426, porcentaje: '5,17%' },
  { nombre: 'Cristian Mella Andau', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', distrito: 6, votos: 30782, porcentaje: '5,23%' },
  { nombre: 'Javier Olivares AvendaÃ±o', partido: 'PDG', bloque: 'Independiente', region: 'ValparaÃ­so', distrito: 6, votos: 31971, porcentaje: '5,44%' },
  { nombre: 'Luis Pardo Sainz', partido: 'RN', bloque: 'Oficialismo', region: 'ValparaÃ­so', distrito: 6, votos: 43341, porcentaje: '7,37%' },
  { nombre: 'Chiara Barchiesi', partido: 'Republicano', bloque: 'Oficialismo', region: 'ValparaÃ­so', distrito: 6, votos: 62737, porcentaje: '10,67%' },
  { nombre: 'BenjamÃ­n Lorca Inzunza', partido: 'Republicano', bloque: 'Oficialismo', region: 'ValparaÃ­so', distrito: 6, votos: 19639, porcentaje: '3,34%' },
  // D7 - ValparaÃ­so (costa)
  { nombre: 'Jorge Brito Hasbun', partido: 'FA', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', distrito: 7, votos: 34122, porcentaje: '6,09%' },
  { nombre: 'Jaime Bassa Mercado', partido: 'FA', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', distrito: 7, votos: 40308, porcentaje: '7,20%' },
  { nombre: 'Luis Cuello PeÃ±a', partido: 'PC', bloque: 'OposiciÃ³n', region: 'ValparaÃ­so', distrito: 7, votos: 37474, porcentaje: '6,69%' },
  { nombre: 'Juan Marcelo Valenzuela HenrÃ­quez', partido: 'PDG', bloque: 'Independiente', region: 'ValparaÃ­so', distrito: 7, votos: 26166, porcentaje: '4,67%' },
  { nombre: 'AndrÃ©s Celis Montt', partido: 'RN', bloque: 'Oficialismo', region: 'ValparaÃ­so', distrito: 7, votos: 27649, porcentaje: '4,94%' },
  { nombre: 'Hotuiti Teao Drago', partido: 'UDI', bloque: 'Oficialismo', region: 'ValparaÃ­so', distrito: 7, votos: 40050, porcentaje: '8,22%' },
  { nombre: 'Luis SÃ¡nchez Ossa', partido: 'Republicano', bloque: 'Oficialismo', region: 'ValparaÃ­so', distrito: 7, votos: 37854, porcentaje: '6,76%' },
  { nombre: 'SebastiÃ¡n Zamora Soto', partido: 'Republicano', bloque: 'Oficialismo', region: 'ValparaÃ­so', distrito: 7, votos: 25755, porcentaje: '4,60%' },
  // D8 - Metropolitana (oeste)
  { nombre: 'Gustavo Gatica Villarroel', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 8, votos: 94444, porcentaje: '12,31%' },
  { nombre: 'Marcos Barraza GÃ³mez', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 8, votos: 26235, porcentaje: '3,42%' },
  { nombre: 'Tatiana Urrutia Herrera', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 8, votos: 33124, porcentaje: '4,32%' },
  { nombre: 'CristiÃ¡n Contreras Radovic', partido: 'PDG', bloque: 'Independiente', region: 'Metropolitana', distrito: 8, votos: 52565, porcentaje: '6,85%' },
  { nombre: 'Mario OlavarrÃ­a RodrÃ­guez', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 8, votos: 23873, porcentaje: '3,11%' },
  { nombre: 'AgustÃ­n Romero Leiva', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 8, votos: 53491, porcentaje: '6,97%' },
  { nombre: 'Enrique Bassaletti Riess', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 8, votos: 47372, porcentaje: '6,18%' },
  { nombre: 'Pier Karlezi Hazleby', partido: 'PNL', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 8, votos: 22867, porcentaje: '2,98%' },
  // D9 - Metropolitana (norte)
  { nombre: 'Boris Barrera Moreno', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 9, votos: 38547, porcentaje: '7,55%' },
  { nombre: 'CÃ©sar Valenzuela Maass', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 9, votos: 23652, porcentaje: '4,63%' },
  { nombre: 'Carlos Cuadrado Prats', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 9, votos: 45282, porcentaje: '8,87%' },
  { nombre: 'Tamara RamÃ­rez RamÃ­rez', partido: 'PDG', bloque: 'Independiente', region: 'Metropolitana', distrito: 9, votos: 23790, porcentaje: '4,66%' },
  { nombre: 'Guillermo RamÃ­rez Diez', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 9, votos: 19093, porcentaje: '3,74%' },
  { nombre: 'JosÃ© Carlos Meza Pereira', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 9, votos: 33721, porcentaje: '6,61%' },
  { nombre: 'Javiera RodrÃ­guez Pascual', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 9, votos: 25145, porcentaje: '4,93%' },
  // D10 - Metropolitana (centro)
  { nombre: 'Gonzalo Winter Etcheberry', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 10, votos: 94085, porcentaje: '14,53%' },
  { nombre: 'Emilia Schneider Videla', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 10, votos: 31212, porcentaje: '4,82%' },
  { nombre: 'Lorena Fries MonleÃ³n', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 10, votos: 5707, porcentaje: '0,88%' },
  { nombre: 'IracÃ­ Hassler Jacob', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 10, votos: 46678, porcentaje: '7,21%' },
  { nombre: 'Jorge Alessandri Vergara', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 10, votos: 56612, porcentaje: '8,74%' },
  { nombre: 'Francisco Orrego GutiÃ©rrez', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 10, votos: 60336, porcentaje: '9,32%' },
  { nombre: 'Hans Marowski Cuevas', partido: 'PNL', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 10, votos: 27976, porcentaje: '4,32%' },
  { nombre: 'JosÃ© Antonio Kast Adriasola', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 10, votos: 56740, porcentaje: '8,76%' },
  // D11 - Metropolitana (oriente)
  { nombre: 'Constanza SchÃ¶nhaut Soto', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 11, votos: 8730, porcentaje: '4,35%' },
  { nombre: 'Diego Schalper SepÃºlveda', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11, votos: 32007, porcentaje: '15,95%' },
  { nombre: 'Claudia Mora Vega', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11, votos: 2777, porcentaje: '1,38%' },
  { nombre: 'Constanza Hube Portus', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11, votos: 26710, porcentaje: '13,31%' },
  { nombre: 'CristiÃ¡n Araya', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11, votos: 16976, porcentaje: '8,46%' },
  { nombre: 'Catalina del Real', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 11, votos: 25417, porcentaje: '12,66%' },
  // D12 - Metropolitana (sur)
  { nombre: 'Daniela Serrano Salazar', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 12, votos: 44742, porcentaje: '7,23%' },
  { nombre: 'Ana MarÃ­a Gazmuri', partido: 'AH', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 12, votos: 57944, porcentaje: '9,37%' },
  { nombre: 'Pamela Jiles Moreno', partido: 'PDG', bloque: 'Independiente', region: 'Metropolitana', distrito: 12, votos: 94478, porcentaje: '15,27%' },
  { nombre: 'Zandra Parisi FernÃ¡ndez', partido: 'PDG', bloque: 'Independiente', region: 'Metropolitana', distrito: 12, votos: 15249, porcentaje: '2,46%' },
  { nombre: 'Ximena OssandÃ³n RodrÃ­guez', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 12, votos: 48711, porcentaje: '7,87%' },
  { nombre: 'Ãlvaro Carter FernÃ¡ndez', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 12, votos: 69157, porcentaje: '11,18%' },
  { nombre: 'Macarena Santelices CaÃ±as', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 12, votos: 23062, porcentaje: '3,73%' },
  // D13 - Metropolitana (sur poniente)
  { nombre: 'Lorena Pizarro Soto', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 13, votos: 30352, porcentaje: '8,17%' },
  { nombre: 'Gael Yeomans Araya', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 13, votos: 46765, porcentaje: '12,55%' },
  { nombre: 'Eduardo DurÃ¡n Salinas', partido: 'RN', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 13, votos: 17558, porcentaje: '4,73%' },
  { nombre: 'Felipe Ross Correa', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 13, votos: 36369, porcentaje: '9,79%' },
  { nombre: 'Valentina Becerra PeÃ±a', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 13, votos: 22199, porcentaje: '5,98%' },
  // D14 - Metropolitana (sur rural)
  { nombre: 'RaÃºl Leiva Carvajal', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 14, votos: 41375, porcentaje: '7,18%' },
  { nombre: 'Marisela SantibÃ¡Ã±ez Novoa', partido: 'PC', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 14, votos: 46760, porcentaje: '8,11%' },
  { nombre: 'Ignacio Achurra DÃ­az', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Metropolitana', distrito: 14, votos: 49264, porcentaje: '8,55%' },
  { nombre: 'Jaime Coloma Ãlamos', partido: 'UDI', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 14, votos: 46157, porcentaje: '8,01%' },
  { nombre: 'Juan IrarrÃ¡zaval Rossel', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 14, votos: 42827, porcentaje: '7,43%' },
  { nombre: 'Diego Vergara RodrÃ­guez', partido: 'Republicano', bloque: 'Oficialismo', region: 'Metropolitana', distrito: 14, votos: 45503, porcentaje: '7,90%' },
  // D15 - O'Higgins (norte)
  { nombre: 'RaÃºl Soto Mardones', partido: 'PPD', bloque: 'OposiciÃ³n', region: "O'Higgins", distrito: 15, votos: 64377, porcentaje: '18,74%' },
  { nombre: 'Fernando Zamorano Peralta', partido: 'PPD', bloque: 'OposiciÃ³n', region: "O'Higgins", distrito: 15, votos: 4599, porcentaje: '1,34%' },
  { nombre: 'Valentina CÃ¡ceres Monsalvez', partido: 'FA', bloque: 'OposiciÃ³n', region: "O'Higgins", distrito: 15, votos: 25746, porcentaje: '7,50%' },
  { nombre: 'Natalia Romero TalguÃ­a', partido: 'UDI', bloque: 'Oficialismo', region: "O'Higgins", distrito: 15, votos: 34258, porcentaje: '9,98%' },
  { nombre: 'Fernando Ugarte Tejeda', partido: 'Republicano', bloque: 'Oficialismo', region: "O'Higgins", distrito: 15, votos: 28533, porcentaje: '8,31%' },
  // D16 - O'Higgins (sur)
  { nombre: 'FÃ©lix BugueÃ±o Sotelo', partido: 'FA', bloque: 'OposiciÃ³n', region: "O'Higgins", distrito: 16, votos: 20172, porcentaje: '7,88%' },
  { nombre: 'Carolina Cucumides CalderÃ³n', partido: 'PS', bloque: 'OposiciÃ³n', region: "O'Higgins", distrito: 16, votos: 22655, porcentaje: '8,85%' },
  { nombre: 'Ricardo Neumann Bertin', partido: 'UDI', bloque: 'Oficialismo', region: "O'Higgins", distrito: 16, votos: 31245, porcentaje: '12,20%' },
  { nombre: 'SebastiÃ¡n Cristoffanini', partido: 'Republicano', bloque: 'Oficialismo', region: "O'Higgins", distrito: 16, votos: 17347, porcentaje: '6,77%' },
  // D17 - Maule (norte)
  { nombre: 'Roberto CeledÃ³n FernÃ¡ndez', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Maule', distrito: 17, votos: 43878, porcentaje: '9,65%' },
  { nombre: 'Priscilla Castillo Gerli', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'Maule', distrito: 17, votos: 46849, porcentaje: '10,30%' },
  { nombre: 'Javier MuÃ±oz Riquelme', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'Maule', distrito: 17, votos: 34294, porcentaje: '7,54%' },
  { nombre: 'Guillermo ValdÃ©s Carmona', partido: 'PDG', bloque: 'Independiente', region: 'Maule', distrito: 17, votos: 12315, porcentaje: '2,71%' },
  { nombre: 'Jorge GuzmÃ¡n Zepeda', partido: 'EvÃ³poli', bloque: 'Oficialismo', region: 'Maule', distrito: 17, votos: 36407, porcentaje: '8,00%' },
  { nombre: 'BenjamÃ­n Moreno Bascur', partido: 'Republicano', bloque: 'Oficialismo', region: 'Maule', distrito: 17, votos: 33754, porcentaje: '7,42%' },
  { nombre: 'GermÃ¡n Verdugo Soto', partido: 'PNL', bloque: 'Oficialismo', region: 'Maule', distrito: 17, votos: 20956, porcentaje: '4,61%' },
  // D18 - Maule (sur)
  { nombre: 'Consuelo Veloso Ãvila', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Maule', distrito: 18, votos: 35583, porcentaje: '14,91%' },
  { nombre: 'Rodrigo RamÃ­rez Parra', partido: 'RN', bloque: 'Oficialismo', region: 'Maule', distrito: 18, votos: 19175, porcentaje: '8,03%' },
  { nombre: 'Daniel Bustos Leal', partido: 'Republicano', bloque: 'Oficialismo', region: 'Maule', distrito: 18, votos: 13475, porcentaje: '5,65%' },
  { nombre: 'CristiÃ¡n Menchaca Munita', partido: 'Republicano', bloque: 'Oficialismo', region: 'Maule', distrito: 18, votos: 32102, porcentaje: '13,45%' },
  // D19 - Ã‘uble
  { nombre: 'Felipe CamaÃ±o CÃ¡rdenas', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'Ã‘uble', distrito: 19, votos: 38559, porcentaje: '11,69%' },
  { nombre: 'Francisco CrisÃ³stomo Llanos', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Ã‘uble', distrito: 19, votos: 15651, porcentaje: '4,75%' },
  { nombre: 'CristÃ³bal MartÃ­nez', partido: 'UDI', bloque: 'Oficialismo', region: 'Ã‘uble', distrito: 19, votos: 24506, porcentaje: '7,43%' },
  { nombre: 'Carlos ChandÃ­a AlarcÃ³n', partido: 'RN', bloque: 'Oficialismo', region: 'Ã‘uble', distrito: 19, votos: 22818, porcentaje: '6,92%' },
  { nombre: 'Sara Concha Smith', partido: 'PSC', bloque: 'Oficialismo', region: 'Ã‘uble', distrito: 19, votos: 18556, porcentaje: '5,63%' },
  // D20 - BiobÃ­o (costa)
  { nombre: 'Ãlvaro Ortiz Vera', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'BiobÃ­o', distrito: 20, votos: 41837, porcentaje: '7,13%' },
  { nombre: 'Antonio Rivas Villalobos', partido: 'PS', bloque: 'OposiciÃ³n', region: 'BiobÃ­o', distrito: 20, votos: 27175, porcentaje: '4,63%' },
  { nombre: 'Patricio Briones MÃ¶ller', partido: 'PDG', bloque: 'Independiente', region: 'BiobÃ­o', distrito: 20, votos: 18160, porcentaje: '3,09%' },
  { nombre: 'Sergio Bobadilla MuÃ±oz', partido: 'UDI', bloque: 'Oficialismo', region: 'BiobÃ­o', distrito: 20, votos: 19213, porcentaje: '3,27%' },
  { nombre: 'Marlene PÃ©rez Cartes', partido: 'UDI', bloque: 'Oficialismo', region: 'BiobÃ­o', distrito: 20, votos: 26600, porcentaje: '4,53%' },
  { nombre: 'Francesca MuÃ±oz GonzÃ¡lez', partido: 'PSC', bloque: 'Oficialismo', region: 'BiobÃ­o', distrito: 20, votos: 53997, porcentaje: '9,20%' },
  { nombre: 'Roberto Arroyo GonzÃ¡lez', partido: 'PSC', bloque: 'Oficialismo', region: 'BiobÃ­o', distrito: 20, votos: 7892, porcentaje: '1,34%' },
  { nombre: 'Paz Charpentier Rajcevich', partido: 'Republicano', bloque: 'Oficialismo', region: 'BiobÃ­o', distrito: 20, votos: 44943, porcentaje: '7,66%' },
  // D21 - BiobÃ­o (interior)
  { nombre: 'Patricio Pinilla Valencia', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'BiobÃ­o', distrito: 21, votos: 20035, porcentaje: '5,13%' },
  { nombre: 'Lilian Betancurt Delgado', partido: 'PDG', bloque: 'Independiente', region: 'BiobÃ­o', distrito: 21, votos: 14469, porcentaje: '3,71%' },
  { nombre: 'Joanna PÃ©rez Olea', partido: 'RN', bloque: 'Oficialismo', region: 'BiobÃ­o', distrito: 21, votos: 32824, porcentaje: '8,41%' },
  { nombre: 'Flor Weisse Novoa', partido: 'UDI', bloque: 'Oficialismo', region: 'BiobÃ­o', distrito: 21, votos: 36115, porcentaje: '9,25%' },
  { nombre: 'CristÃ³bal Urruticoechea RÃ­os', partido: 'PNL', bloque: 'Oficialismo', region: 'BiobÃ­o', distrito: 21, votos: 27947, porcentaje: '7,16%' },
  // D22 - La AraucanÃ­a (norte)
  { nombre: 'Andrea Parra Sauterel', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'La AraucanÃ­a', distrito: 22, votos: 14430, porcentaje: '7,42%' },
  { nombre: 'Juan Carlos BeltrÃ¡n Silva', partido: 'RN', bloque: 'Oficialismo', region: 'La AraucanÃ­a', distrito: 22, votos: 25762, porcentaje: '13,25%' },
  { nombre: 'Eduardo Cretton Rebolledo', partido: 'UDI', bloque: 'Oficialismo', region: 'La AraucanÃ­a', distrito: 22, votos: 29658, porcentaje: '15,25%' },
  { nombre: 'Gloria NaveillÃ¡n Arriagada', partido: 'PNL', bloque: 'Oficialismo', region: 'La AraucanÃ­a', distrito: 22, votos: 16389, porcentaje: '8,43%' },
  // D23 - La AraucanÃ­a (sur)
  { nombre: 'JosÃ© Montalva Feuerhake', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'La AraucanÃ­a', distrito: 23, votos: 33884, porcentaje: '7,91%' },
  { nombre: 'Coca Ã‘anco VÃ¡squez', partido: 'FA', bloque: 'OposiciÃ³n', region: 'La AraucanÃ­a', distrito: 23, votos: 28418, porcentaje: '6,63%' },
  { nombre: 'Flor Contreras Vivallo', partido: 'PDG', bloque: 'Independiente', region: 'La AraucanÃ­a', distrito: 23, votos: 10759, porcentaje: '2,51%' },
  { nombre: 'TomÃ¡s Kast Sommerhoff', partido: 'EvÃ³poli', bloque: 'Oficialismo', region: 'La AraucanÃ­a', distrito: 23, votos: 34870, porcentaje: '8,14%' },
  { nombre: 'RenÃ© Manuel GarcÃ­a GarcÃ­a', partido: 'RN', bloque: 'Oficialismo', region: 'La AraucanÃ­a', distrito: 23, votos: 18105, porcentaje: '4,23%' },
  { nombre: 'Stephan Schubert Rubio', partido: 'Republicano', bloque: 'Oficialismo', region: 'La AraucanÃ­a', distrito: 23, votos: 40705, porcentaje: '9,50%' },
  { nombre: 'CristiÃ¡n Neira MartÃ­nez', partido: 'Republicano', bloque: 'Oficialismo', region: 'La AraucanÃ­a', distrito: 23, votos: 14010, porcentaje: '3,27%' },
  // D24 - Los RÃ­os
  { nombre: 'Marcos Ilabaca Cerda', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Los RÃ­os', distrito: 24, votos: 33641, porcentaje: '13,00%' },
  { nombre: 'MatÃ­as FernÃ¡ndez Hartwig', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Los RÃ­os', distrito: 24, votos: 26179, porcentaje: '10,12%' },
  { nombre: 'Omar Sabat FernÃ¡ndez', partido: 'UDI', bloque: 'Oficialismo', region: 'Los RÃ­os', distrito: 24, votos: 26518, porcentaje: '10,25%' },
  { nombre: 'Daniel Valenzuela VÃ¡squez', partido: 'RN', bloque: 'Oficialismo', region: 'Los RÃ­os', distrito: 24, votos: 15031, porcentaje: '5,81%' },
  { nombre: 'Leandro Kunstmann Rojas', partido: 'Republicano', bloque: 'Oficialismo', region: 'Los RÃ­os', distrito: 24, votos: 23371, porcentaje: '9,03%' },
  // D25 - Los Lagos (norte)
  { nombre: 'HÃ©ctor BarrÃ­a Angulo', partido: 'PDC', bloque: 'OposiciÃ³n', region: 'Los Lagos', distrito: 25, votos: 32211, porcentaje: '13,74%' },
  { nombre: 'Emilia Nuyado AncapichÃºn', partido: 'PS', bloque: 'OposiciÃ³n', region: 'Los Lagos', distrito: 25, votos: 30571, porcentaje: '13,04%' },
  { nombre: 'Daniel Lilayu Winnimann', partido: 'UDI', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 25, votos: 24795, porcentaje: '10,58%' },
  { nombre: 'Paulina MuÃ±oz AlarcÃ³n', partido: 'PNL', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 25, votos: 20229, porcentaje: '8,63%' },
  // D26 - Los Lagos (sur)
  { nombre: 'HÃ©ctor Ulloa Aguilera', partido: 'PPD', bloque: 'OposiciÃ³n', region: 'Los Lagos', distrito: 26, votos: 20441, porcentaje: '6,88%' },
  { nombre: 'Alejandro Bernales Mardones', partido: 'Liberal', bloque: 'OposiciÃ³n', region: 'Los Lagos', distrito: 26, votos: 35435, porcentaje: '11,93%' },
  { nombre: 'Ãlex NahuelquÃ­n', partido: 'PDG', bloque: 'Independiente', region: 'Los Lagos', distrito: 26, votos: 30324, porcentaje: '10,21%' },
  { nombre: 'Mauro GonzÃ¡lez Villarroel', partido: 'RN', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 26, votos: 35202, porcentaje: '11,85%' },
  { nombre: 'Claudia Reyes Larenas', partido: 'Republicano', bloque: 'Oficialismo', region: 'Los Lagos', distrito: 26, votos: 30865, porcentaje: '10,39%' },
  // D27 - AysÃ©n
  { nombre: 'RenÃ© Alinco Bustos', partido: 'FREVS', bloque: 'OposiciÃ³n', region: 'AysÃ©n', distrito: 27, votos: 8889, porcentaje: '14,26%' },
  { nombre: 'Andrea MacÃ­as Palma', partido: 'PS', bloque: 'OposiciÃ³n', region: 'AysÃ©n', distrito: 27, votos: 9625, porcentaje: '15,44%' },
  { nombre: 'Alejandra Valdebenito RodrÃ­guez', partido: 'UDI', bloque: 'Oficialismo', region: 'AysÃ©n', distrito: 27, votos: 6451, porcentaje: '10,35%' },
  // D28 - Magallanes
  { nombre: 'Javiera Morales Ortiz', partido: 'FA', bloque: 'OposiciÃ³n', region: 'Magallanes', distrito: 28, votos: 9359, porcentaje: '9,30%' },
  { nombre: 'Alejandro Riquelme Herrera', partido: 'Republicano', bloque: 'Oficialismo', region: 'Magallanes', distrito: 28, votos: 12685, porcentaje: '12,61%' },
  { nombre: 'Carlos Bianchi Chelech', partido: 'Independiente', bloque: 'Independiente', region: 'Magallanes', distrito: 28, votos: 24954, porcentaje: '24,81%' },
]
